### ISSUE TITLE
Consider adding an "Alternatives" section that shows the ternary hack

### ISSUE THREAD

**Issue by jcbhmr** [haya14busa/action-cond#25]
Would be good to show why/when you should/could use this action instead of the ternary hack 

```yml
steps:
  - uses: actions/checkout@v3
  - run: npm run build ${{ inputs.production && '--production' || '' }}
    # => adds '--production' if box is checked, '' if not
```

Other good things that could be linked to:
- https://github.com/actions/runner/issues/409
- https://github.com/orgs/community/discussions/75928
- https://pablissimo.com/1137/github-actions-ternary-operators-and-default-values
- https://github.com/orgs/community/discussions/26738
- https://github.com/orgs/community/discussions/68534
- https://7tonshark.com/posts/github-actions-ternary-operator/

Want to explain and answer this question: Why would a user use this:

```yml
steps:
- uses: haya14busa/action-cond@v1
  id: condval
  with:
    cond: ${{ github.event_name == 'pull_request' }}
    if_true: "value for pull request event"
    if_false: "value for non pull request event"
- name: Use conditional value
  run: echo "${{ steps.condval.outputs.value }}"
```
instead of this?
```yml
steps:
  - run: echo "$VALUE"
    env:
      VALUE: |
        ${{ github.event_name == 'pull_request'
          && 'value for pull request event'
          || 'value for non pull request event }}
```

Something like "if you have a lot of chained if conditions this action is a good fit for you" or something would be quite helpful.

**Comment by jannikschaper** [comment]
Especially considering GitHub officially documents this feature as "ternary operator like behavior" ([src](https://docs.github.com/en/actions/learn-github-actions/expressions#example)):

![image](https://github.com/haya14busa/action-cond/assets/150021423/0b70dd02-88fb-4ac8-aeed-928e687a5e3f)

**Comment by ferdnyc** [comment]
I suspect the primary answer to this question is, "This action was created long before the built-in ternary behavior was available" (or at very least _documented_, as the section @jannikschaper quotes [was only added to the docs in June 2023](https://github.com/github/docs/pull/24357)).

Today, you probably _shouldn't_ use this action in favor of GitHub's built-in ternary-like support, except perhaps in very specific circumstances. (Like when you really need the `if_true` output to be `false`, since GitHub's example makes it clear that it can't do that.)

**Comment by ferdnyc** [comment]
That being said, one nice thing about using this action — instead of, say, setting envvars like in the GitHub example — is that you don't have to deal with shell parsing of the results.

I have some workflows where I use the action to generate CMake arguments under certain conditions. Using this:

```yml
= id: use-foo
  uses: haya14busa/action-cond@v1
  with:
    cond: ${{ matrix.compiler.cc == 'clang' && runner.os == 'linux' }}
    if_true: "\"-DENABLE_FOO:BOOL=1\"" "\"-DFoo_ROOT:PATH=./foo\""
```
and
```yml
- run: |
    cmake -B build -S . ${{ steps.use-foo.outputs.value }}
```

is a _lot_ easier than setting an envvar and having to worry about getting the quoting right. I trust, at this point, that the action will preserve the escaped quoting, and cause the command to be generated correctly.

Using either envvars _or_ the ternary-like hack, getting the quoting right seems like more of a headache than it's worth.

(Also, TBH I'm not entirely sure how the ternary hack deals with _multiple_ AND-ed conditions like that.)

Is it this?

```yml
${{ matrix.compiler.cc == 'clang' && runner.os == 'linux' && '-DENABLE_FOO=1' || '' }}
```

Or does it need something (parentheses?) around the non-outputting parts, like...

```yml
${{ ( matrix.compiler.cc == 'clang' && runner.os == 'linux' ) && '-DENABLE_FOO=1' || '' }}
```

Who knows? `¯\_(ツ)_/¯`
